import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { DarkThemeToggle, ThemeModeScript } from "flowbite-react";
import "./globals.css";
import CustomNavbar from "./components/custom_navbar";
import { verifySession } from "./_lib/session";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Prueba tecnica",
  description: "Generated by create flowbite react",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ThemeModeScript />
      </head>
      <body className={inter.className + " flex min-h-screen flex-col"}>
        <CustomNavbar />
        {children}
      </body>
    </html>
  );
}
